bind: ":8080"

sources:
  - id: example-opal
    url: http://opal_client:7000
    token: ""
    advertisedAddress: optoggles:8080

target:
  targetType: launchdarkly
  targetSpec:
    # Replace with your API token
    launchdarklyToken: ""

toggles:
  - key: "cs-feature"
    usersPolicy:
      source: example-opal
      package: "validateClientId"
      rule: "customer_support_only"
    spec:
      name: "Customer Support Only Feature"
      projKey: "default"
      environments: [ "production", "test" ]