name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Extract branch/tag name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF#refs/*/} | sed 's/\//_/g')"
        id: extract_branch
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: permitio/optoggles:${{ steps.extract_branch.outputs.ref }}
      - name: Build and push latest
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: permitio/optoggles:latest
